#+STARTUP: showall
#+TITLE: Edit with emacs Everywhere
#+OPTIONS: ^:nil

* Introduction

This module allows editing with emacs anywhere in OS X.

See this demo: [[https://youtu.be/jYUKYpXL6rI]]

In any text field in any application, one can summon Emacs. 

1. User is editing textfield, presses:
  - /Option-2/: send all text in field
  - /Option-3/: send the current selection
2. Emacs shows the currently edited text in a new buffer (it can be the entire text field or the current selection)
3. User edits buffer (in org-mode)
4. User presses /C-C C-C/ to send back text to the original text field replacing selection


* Installation

** Hammerspoon

place this folder inside the ~/.hammerspoon/Spoons directory such that you have (the .spoon extension is important):

#+begin_src sh
 ~/.hammerspoon/Spoons/editWithEmacs.spoon
#+end_src



Modify your ~/.hammerspoon/init.lua and add:

#+begin_src lua
hs.loadSpoon("editWithEmacs")
#+end_src

** emacs

Copy the file [[./hammerspoon.el]] to your .emacs.d directory and make sure it is loaded

* Testing installation

Make sure you can summon hammerspoon from emacs. Call the interactive function /hammerpoon-test/

You should see a message in the screen. If not, something is wrong


* How to use 

See the bottom of [[./init.lua]]. There are two commands:

The first is edit in emacs selecting all text in the field. The second uses the current selection.
You can change the default keys if you choose.

#+begin_src lua
hs.hotkey.bind({"alt"}, '2', nil, function()
      edit_in_emacs(true)
end)

-- edit by using current selection
hs.hotkey.bind({"alt"}, '3', nil, function()
      edit_in_emacs(false)
end)
#+end_src


In the text field you are editing, call either command. If emacs is running, its most current window will be shown, and a new buffer displayed
with the text to edit. Simply press Ctrl-C Ctrl-C to finish editing. After this you should be back in the field you were editing

* Limitations

- This method is non-reentrant. This means you can only edit one field at a time. You do not need to send the text back to the text-field. 
  You can use edit-with-emacs again without any undesirable effect.
- It is currently sending commands directly to emacs via the keyboard. Thus, emacs should be ready to accept commands
- If something goes wrong and the text does not appear, you can retrieve it from emacs. Switch to the _hs_edit buffer and you will see the text you were editing.
  This buffer will be reused

* Bugs/fixes?

- Please open an issue/pull-request
